version: "3.8"
services:
  api:
    build: .
    ports:
      - "19093:19093"
    # restart: on-failure
    volumes:
      - api:/usr/local/api-volume
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack

  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
        MYSQL_DATABASE: sensibull
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        MYSQL_ROOT_HOST: fullstack-mysql
      # - MYSQL_ROOT_HOST=${DB_HOST} 
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      # - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - MYSQL_ROOT_HOST:localhost
      # - MYSQL_USER:docker
      # - MYSQL_PASSWORD:docker
      # - MYSQL_DATABASE:sensibull
      # - MYSQL_ROOT_PASSWORD:root
    volumes:
      - database_mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - fullstack
  
      
volumes:
  api:
  database_mysql:    

networks:
  fullstack: