version: "3.8"
services:
  

  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
   
    volumes:
      - database_mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - fullstack
  api:
    build: .
    ports:
      - "19093:19093"
    # restart: on-failure
    volumes:
      - api:/usr/local/api-volume
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      
volumes:
  api:
  database_mysql:    

networks:
  fullstack: